language: node_js
node_js:
- '10'
branchs:
  only:
  - master
addons:
  ssh_known_hosts:
  - 47.101.52.166
script:
- npm run build
notifications:
  email:
    recipients:
    - 576359186@qq.com
    on_success: always
    on_failure: always
after_success:
- chmod -R 600 ~/.ssh/id_rsa
#- cat ~/.ssh/id_rsa
- scp -o StrictHostKeyChecking=no -v -r ./dist/* travis@47.101.52.166:/usr/justdoit_front
